# Introduction to Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
print(a)

[1 2 3 4]


In [4]:
a

array([1, 2, 3, 4])

In [5]:
print (a[1])

2


In [6]:
a[1]

2

In [8]:
b = np.array([[1,2], [3,4], [5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

**b.ndim tells us the dimension of the array**

In [12]:
b.ndim

2

__b.itemsize tells ud the size of each item in the memory__

In [14]:
b.itemsize

4

__b.shape will tell us the shape of the array__

In [17]:
b.shape

(3, 2)