# Introduction to Numpy

In [1]:
import numpy as np

## Basic Operations

In [12]:
a = np.array([1,2,3,4])

In [3]:
print(a)

[1 2 3 4]


In [4]:
a

array([1, 2, 3, 4])

In [5]:
print (a[1])

2


In [6]:
a[1]

2

In [13]:
a.dtype

dtype('int32')

In [10]:
b = np.array([[1,2], [3,4], [5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

**b.ndim tells us the dimension of the array**

In [12]:
b.ndim

2

__b.itemsize tells us the memory size of each element__

In [14]:
b.itemsize

4

__b.shape will tell us the shape of the array__

In [17]:
b.shape

(3, 2)

In [4]:
b = np.array([[1,2], [3,4], [5,6]], dtype = np.float64)
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

__b.size tells us the total number of elements in the array while b.itemsize tells us memory size of each element__

In [5]:
b.size

6

In [6]:
b.itemsize

8

In [7]:
b.shape

(3, 2)

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
l = range(0,5)
l

range(0, 5)

__np.arange(1, 7) creates a NumPy array with values ranging from 1 to 6 (excluding 7)__

In [25]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

## Numpy String Functions

__Concatenation example__

In [30]:
np.char.add(['hello', 'hii'], ['adios', 'byee'])

array(['helloadios', 'hiibyee'], dtype='<U10')

In [31]:
print(np.char.add(['hello', 'hii'], ['adios', 'byee']))

['helloadios' 'hiibyee']


In [34]:
np.char.multiply(['hello '], [4])

array(['hello hello hello hello '], dtype='<U24')

In [35]:
print(np.char.multiply(['hello '], [4]))

['hello hello hello hello ']


In [36]:
print(np.char.multiply('hello ', 4))

hello hello hello hello 


In [37]:
print(np.char.center('hello', 20, fillchar = '-'))

-------hello--------


In [2]:
print(np.char.capitalize('hello world'))

Hello world


In [3]:
print(np.char.title('hello world'))

Hello World


In [8]:
print(np.char.upper('hello world'))
print(np.char.upper(['hello world']))

HELLO WORLD
['HELLO WORLD']


In [9]:
print(np.char.lower('HELLO WORLD'))
print(np.char.lower(['HELLO WORLD']))

hello world
['hello world']


In [10]:
print(np.char.split('How are you doing?'))

['How', 'are', 'you', 'doing?']


In [13]:
print(np.char.splitlines('How are you \n doing?'))

['How are you ', ' doing?']


__strip removes the leading and trailing letters or spaces or symbols__

In [14]:
print(np.char.strip(['anita', 'manisha', 'admin'], 'a'))

['nit' 'manish' 'dmin']


In [15]:
print(np.char.join([':', '-'], ['dmy', 'ymd']))

['d:m:y' 'y-m-d']
