# Introduction to Numpy

In [14]:
import numpy as np

## Basic Operations

In [12]:
a = np.array([1,2,3,4])

In [3]:
print(a)

[1 2 3 4]


In [4]:
a

array([1, 2, 3, 4])

In [5]:
print (a[1])

2


In [6]:
a[1]

2

In [13]:
a.dtype

dtype('int32')

In [10]:
b = np.array([[1,2], [3,4], [5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

**b.ndim tells us the dimension of the array**

In [12]:
b.ndim

2

__b.itemsize tells us the memory size of each element__

In [14]:
b.itemsize

4

__b.shape will tell us the shape of the array__

In [17]:
b.shape

(3, 2)

In [4]:
b = np.array([[1,2], [3,4], [5,6]], dtype = np.float64)
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

__b.size tells us the total number of elements in the array while b.itemsize tells us memory size of each element__

In [5]:
b.size

6

In [6]:
b.itemsize

8

In [7]:
b.shape

(3, 2)

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
l = range(0,5)
l

range(0, 5)

__np.arange(1, 7) creates a NumPy array with values ranging from 1 to 6 (excluding 7)__

In [25]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

## Numpy String Functions